version: '2'

services:


  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
        - lanchonete-network


  myapp:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: lanchonete
    environment:
      - SPRING_JPA_DATABASE=POSTGRESQL
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cliente
      - SERVER_PORT=8080
      - TOKEN_APP=APP_USR-151362775144770-012219-ad26be97b5a2ceab5965aaf6409a0d70-1650421194
      - GATEWAY_DATA_PAYMENT_NOTIFICATION=https://eog65tb4u88eyt7.m.pipedream.net
    depends_on:
      - db
    ports:
        - "8080:8080"
    networks:
      - lanchonete-network



networks:
  lanchonete-network:
    driver: bridge